name: bsud crate.io publishing
on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  publish:
    environment: publish
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
    - name: Stable Rust with rustfmt
      uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # v1
      with:
        toolchain: stable
        components: rustfmt
    - name: Cargo publish
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}